"""empty message

Revision ID: 153d87fd55de
Revises: 90fac3c32904
Create Date: 2025-09-12 22:56:12.117459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '153d87fd55de'
down_revision = '90fac3c32904'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_constraint('recipe_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.create_unique_constraint('recipe_name_key', ['name'])

    # ### end Alembic commands ###
