"""empty message

Revision ID: 253ffcefd92f
Revises: 25d9091f38e5
Create Date: 2025-09-29 00:53:21.103993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '253ffcefd92f'
down_revision = '25d9091f38e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredients', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('ingredients')

    # ### end Alembic commands ###
