"""empty message

Revision ID: 3a53aaf83d11
Revises: 153d87fd55de
Create Date: 2025-09-14 02:40:29.269744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a53aaf83d11'
down_revision = '153d87fd55de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chef', schema=None) as batch_op:
        batch_op.drop_constraint('chef_email_key', type_='unique')
        batch_op.drop_constraint('chef_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chef', schema=None) as batch_op:
        batch_op.create_unique_constraint('chef_name_key', ['name'])
        batch_op.create_unique_constraint('chef_email_key', ['email'])

    # ### end Alembic commands ###
