"""empty message

Revision ID: 6d33ea36f1eb
Revises: c79269ef0c09
Create Date: 2025-09-14 01:50:44.538275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d33ea36f1eb'
down_revision = 'c79269ef0c09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utensil_recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('utensil_recipe_chef_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'recipe', ['recipe_id'], ['id'])
        batch_op.drop_column('chef_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utensil_recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chef_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('utensil_recipe_chef_id_fkey', 'chef', ['chef_id'], ['id'])
        batch_op.drop_column('recipe_id')

    # ### end Alembic commands ###
