"""empty message

Revision ID: 90fac3c32904
Revises: 1fb000e8d0e9
Create Date: 2025-09-12 22:54:07.202923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90fac3c32904'
down_revision = '1fb000e8d0e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_constraint('recipe_description_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.create_unique_constraint('recipe_description_key', ['description'])

    # ### end Alembic commands ###
