"""empty message

Revision ID: c79269ef0c09
Revises: e5850aa3ae99
Create Date: 2025-09-12 23:48:24.299460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c79269ef0c09'
down_revision = 'e5850aa3ae99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utensil_recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chef_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('utensil_recipe_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'chef', ['chef_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utensil_recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('utensil_recipe_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_column('chef_id')

    # ### end Alembic commands ###
