"""empty message

Revision ID: e11ed971138a
Revises: 13d6b8a75d48
Create Date: 2025-09-10 22:05:54.650316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e11ed971138a'
down_revision = '13d6b8a75d48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stars', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calification')
    # ### end Alembic commands ###
